src/Entity/Servant.php
<?php

namespace App\Entity;

use App\Entity\Enum\Gender;
use App\Repository\ServantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ServantRepository::class)]
class Servant
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $firstName = null;

    #[ORM\Column(length: 50)]
    private ?string $lastName1 = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $lastName2 = null;

    #[ORM\Column(enumType: Gender::class, nullable: true)]
    private ?Gender $gender = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(nullable: true)]
    private ?int $birthMonth = null;

    #[ORM\Column(nullable: true)]
    private ?int $birthDay = null;

    #[ORM\Column(nullable: true)]
    private ?int $key = null;

    /**
     * @var Collection<int, UnitAssignment>
     */
    #[ORM\OneToMany(targetEntity: UnitAssignment::class, mappedBy: 'servant')]
    private Collection $unitAssignments;

    public function __construct()
    {
        $this->unitAssignments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): static
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName1(): ?string
    {
        return $this->lastName1;
    }

    public function setLastName1(string $lastName1): static
    {
        $this->lastName1 = $lastName1;

        return $this;
    }

    public function getLastName2(): ?string
    {
        return $this->lastName2;
    }

    public function setLastName2(?string $lastName2): static
    {
        $this->lastName2 = $lastName2;

        return $this;
    }

    public function getGender(): ?Gender
    {
        return $this->gender;
    }

    public function setGender(Gender $gender): static
    {
        $this->gender = $gender;

        return $this;
    }

    public function getGenderString(): string
    {
        return $this->gender->value ?? '';
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getBirthMonth(): ?int
    {
        return $this->birthMonth;
    }

    public function setBirthMonth(?int $birthMonth): static
    {
        $this->birthMonth = $birthMonth;

        return $this;
    }

    public function getBirthDay(): ?int
    {
        return $this->birthDay;
    }

    public function setBirthDay(?int $birthDay): static
    {
        $this->birthDay = $birthDay;

        return $this;
    }

    public function getKey(): ?int
    {
        return $this->key;
    }

    public function setKey(?int $key): static
    {
        $this->key = $key;

        return $this;
    }

    /**
     * @return Collection<int, UnitAssignment>
     */
    public function getUnitAssignments(): Collection
    {
        return $this->unitAssignments;
    }

    public function addUnitAssignment(UnitAssignment $unitAssignment): static
    {
        if (!$this->unitAssignments->contains($unitAssignment)) {
            $this->unitAssignments->add($unitAssignment);
            $unitAssignment->setServant($this);
        }

        return $this;
    }

    public function removeUnitAssignment(UnitAssignment $unitAssignment): static
    {
        if ($this->unitAssignments->removeElement($unitAssignment)) {
            // set the owning side to null (unless already changed)
            if ($unitAssignment->getServant() === $this) {
                $unitAssignment->setServant(null);
            }
        }

        return $this;
    }
}

src/Form/ServantType.php
<?php

namespace App\Form;

use App\Entity\Servant;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ServantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('firstName')
            ->add('lastName1')
            ->add('lastName2')
            ->add('gender')
            ->add('email')
            ->add('birthMonth')
            ->add('birthDay')
            ->add('key')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Servant::class,
        ]);
    }
}

src/Controller/ServantController.php
<?php

namespace App\Controller;

use App\Entity\Servant;
use App\Form\ServantType;
use App\Repository\ServantRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/servant')]
final class ServantController extends AbstractController
{
    #[Route(name: 'app_servant_index', methods: ['GET'])]
    public function index(ServantRepository $servantRepository): Response
    {
        return $this->render('servant/index.html.twig', [
            'servants' => $servantRepository->findWithGeneratingUnits(),
        ]);
    }

    #[Route('/new', name: 'app_servant_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $servant = new Servant();
        $form = $this->createForm(ServantType::class, $servant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($servant);
            $entityManager->flush();

            return $this->redirectToRoute('app_servant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('servant/new.html.twig', [
            'servant' => $servant,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_servant_show', methods: ['GET'])]
    public function show(Servant $servant): Response
    {
        return $this->render('servant/show.html.twig', [
            'servant' => $servant,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_servant_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Servant $servant, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ServantType::class, $servant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_servant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('servant/edit.html.twig', [
            'servant' => $servant,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_servant_delete', methods: ['POST'])]
    public function delete(Request $request, Servant $servant, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$servant->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($servant);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_servant_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/servant/_delete_form.html.twig
<form method="post" action="{{ path('app_servant_delete', {'id': servant.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ servant.id) }}">
    <button class="btn">Delete</button>
</form>

templates/servant/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/servant/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Servant{% endblock %}

{% block body %}
    <h1>Edit Servant</h1>

    {{ include('servant/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_servant_index') }}">back to list</a>

    {{ include('servant/_delete_form.html.twig') }}
{% endblock %}

templates/servant/index.html.twig
{% extends 'content_base.html.twig' %}

{% block content_title %}Servidores públicos{% endblock %}

{% block body %}
    <h1>Servant index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>FirstName</th>
                <th>LastName1</th>
                <th>LastName2</th>
                <th>Gender</th>
                <th>Email</th>
                <th>BirthMonth</th>
                <th>BirthDay</th>
                <th>Key</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for servant in servants %}
            <tr>
                <td>{{ servant.id }}</td>
                <td>{{ servant.firstName }}</td>
                <td>{{ servant.lastName1 }}</td>
                <td>{{ servant.lastName2 }}</td>
                <td>{{ servant.genderString }}</td>
                <td>{{ servant.email }}</td>
                <td>{{ servant.birthMonth }}</td>
                <td>{{ servant.birthDay }}</td>
                <td>{{ servant.key }}</td>
                <td>
                    <a href="{{ path('app_servant_show', {'id': servant.id}) }}">show</a>
                    <a href="{{ path('app_servant_edit', {'id': servant.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_servant_new') }}">Create new</a>
{% endblock %}

templates/servant/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Servant{% endblock %}

{% block body %}
    <h1>Create new Servant</h1>

    {{ include('servant/_form.html.twig') }}

    <a href="{{ path('app_servant_index') }}">back to list</a>
{% endblock %}

templates/servant/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Servant{% endblock %}

{% block body %}
    <h1>Servant</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ servant.id }}</td>
            </tr>
            <tr>
                <th>FirstName</th>
                <td>{{ servant.firstName }}</td>
            </tr>
            <tr>
                <th>LastName1</th>
                <td>{{ servant.lastName1 }}</td>
            </tr>
            <tr>
                <th>LastName2</th>
                <td>{{ servant.lastName2 }}</td>
            </tr>
            <tr>
                <th>Gender</th>
                <td>{{ servant.gender }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ servant.email }}</td>
            </tr>
            <tr>
                <th>BirthMonth</th>
                <td>{{ servant.birthMonth }}</td>
            </tr>
            <tr>
                <th>BirthDay</th>
                <td>{{ servant.birthDay }}</td>
            </tr>
            <tr>
                <th>Key</th>
                <td>{{ servant.key }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_servant_index') }}">back to list</a>

    <a href="{{ path('app_servant_edit', {'id': servant.id}) }}">edit</a>

    {{ include('servant/_delete_form.html.twig') }}
{% endblock %}